{
  "generated": true,
  "tiers": {
    "TIER1": [
      39,
      140,
      135,
      78,
      61,
      2,
      3,
      848
    ],
    "TIER1B": [
      88,
      94,
      203,
      179,
      253,
      71,
      128
    ],
    "CUPS_ELITE": [
      45,
      81,
      137,
      66,
      556
    ],
    "NT_MAJOR": [
      1,
      4,
      762
    ]
  }
}